export const BANNED_SYMBOLS: string[] = [
  "IMX/USDT", "IMXUSDT",
  "JUP/USDT", "JUPUSDT",
  "APT/USDT", "APTUSDT",
  "ONDO/USDT", "ONDOUSDT",
  "LDO/USDT", "LDOUSDT",
  "WOO/USDT", "WOOUSDT",
  "1INCH/USDT", "1INCHUSDT",
  "JTO/USDT", "JTOUSDT", "JOT/USDT", "JOTUSDT",
  "HBAR/USDT", "HBARUSDT",
  "BOME/USDT", "BOMEUSDT",
  "GALA/USDT", "GALAUSDT",
  "THETA/USDT", "THETAUSDT",
  "GMT/USDT", "GMTUSDT",
  "YFI/USDT", "YFIUSDT",
  "BNB/USDT", "BNBUSDT",
  "GRT/USDT", "GRTUSDT"
];

const RAW_COINS: string[] = [
  "BTC/USDT", "ETH/USDT", "BNB/USDT", "SOL/USDT", "XRP/USDT", "ADA/USDT", "DOGE/USDT", "AVAX/USDT", "LINK/USDT", "DOT/USDT",
  "POL/USDT", "SHIB/USDT", "LTC/USDT", "TRX/USDT", "UNI/USDT", "NEAR/USDT", "FIL/USDT", "ATOM/USDT", "LDO/USDT", "OP/USDT",
  "APT/USDT", "ARB/USDT", "SUI/USDT", "TIA/USDT", "SEI/USDT", "INJ/USDT", "ICP/USDT", "ETC/USDT", "BCH/USDT", "XLM/USDT",
  "HBAR/USDT", "GRT/USDT", "IMX/USDT", "RENDER/USDT", "MKR/USDT", "AAVE/USDT", "RUNE/USDT", "FTM/USDT", "THETA/USDT", "ALGO/USDT",
  "EGLD/USDT", "STX/USDT", "SAND/USDT", "MANA/USDT", "AXS/USDT", "GALA/USDT", "PEPE/USDT", "MINA/USDT", "CAKE/USDT", "DYDX/USDT",
  "CRV/USDT", "WOO/USDT", "GMT/USDT", "WLD/USDT", "ORDI/USDT", "1INCH/USDT", "MASK/USDT", "FET/USDT", "JASMY/USDT", "ENS/USDT",
  "BONK/USDT", "ENJ/USDT", "ANKR/USDT", "ZIL/USDT", "KAVA/USDT", "GMX/USDT", "COMP/USDT", "SNX/USDT", "YFI/USDT", "SUSHI/USDT",
  "STORJ/USDT", "ZRX/USDT", "BAT/USDT", "ONE/USDT", "RVN/USDT", "WIF/USDT", "KSM/USDT", "NEO/USDT", "QTUM/USDT", "EOS/USDT",
  "IOTA/USDT", "VET/USDT", "CHZ/USDT", "MANTA/USDT", "ALT/USDT", "JUP/USDT", "PYTH/USDT", "STRK/USDT", "DYM/USDT", "IO/USDT",
  "FLOKI/USDT", "XAI/USDT", "PENDLE/USDT", "JTO/USDT", "AXL/USDT", "BOME/USDT", "ENA/USDT", "ONDO/USDT", "TAO/USDT", "ASTR/USDT"
];

export const HUNDRED_COINS: string[] = RAW_COINS.filter(c => !BANNED_SYMBOLS.includes(c));

